{ pkgs, config, ... }:
{
  imports = [
    ./acme.nix
    ./adam-site.nix
    ./adguard.nix
    ./caldav.nix
    ./clamav.nix
    ./dnsmasq.nix
    ./ente.nix
    ./fileshelter.nix
    ./games
    ./gitea-runner.nix
    ./gitea.nix
    ./github-runner.nix
    ./gitolite.nix
    ./hardening.nix
    ./kavita.nix
    ./kop-fileshare.nix
    ./kop-monitor.nix
    ./kop-pvlog.nix
    ./kubernetes.nix
    ./nginx.nix
    ./opensnitch.nix
    ./plausible.nix
    ./smartd.nix
    ./smartd-exporter.nix
    ./syncthing.nix
    ./wireguard.nix
  ];
}
