{
 "title": "Nginxlog",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests by response status total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (nginxlog_http_response_count_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by response status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginxlog_http_response_count_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Parse errors total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginxlog_parse_errors_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Requests by method total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (nginxlog_http_response_count_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginxlog_http_response_count_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(nginxlog_http_response_size_bytes[$__rate_interval])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  }
 ]
}